---
- name: Debug Foreman variables
  hosts: foreman_almalinux10_kubernetescontrolplanenode
  gather_facts: false

  tasks:
    - name: Dump all foreman variables
      ansible.builtin.debug:
        var: foreman

    - name: Dump all hostvars
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
