---
- name: Label each worker node
  ansible.builtin.command: >
    kubectl label node {{ item }}
    node-role.kubernetes.io/worker=worker
    --overwrite
  loop: "{{ groups['foreman_almalinux10_kubernetesworkernode'] }}"
  register: _label_result
  until: _label_result.rc == 0
  retries: 18
  delay: 10
  changed_when: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Verify worker labels applied
  ansible.builtin.command: kubectl get nodes -o wide
  changed_when: false
  register: nodes_labeled
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Print labeled node list
  ansible.builtin.debug:
    var: nodes_labeled.stdout_lines
