---
- name: Remove k8s-api A record from FreeIPA
  community.general.ipa_dnsrecord:
    ipa_user: admin
    ipa_pass: "{{ vault_ipaadmin_password }}"
    ipa_host: "{{ vault_ipa_server }}"
    zone_name: "{{ vault_ipadomain }}"
    record_name: "{{ k8s_api_endpoint | regex_replace('\\.' + vault_ipadomain + '$', '') }}"
    record_type: A
    state: absent

- name: Remove *.k8s wildcard A record from FreeIPA
  community.general.ipa_dnsrecord:
    ipa_user: admin
    ipa_pass: "{{ vault_ipaadmin_password }}"
    ipa_host: "{{ vault_ipa_server }}"
    zone_name: "{{ vault_ipadomain }}"
    record_name: "*.k8s"
    record_type: A
    state: absent

- name: Remove host from Foreman
  theforeman.foreman.host:
    username: "{{ foreman_user }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ item.name }}.{{ foreman_domain }}"
    state: absent
  loop: "{{ vms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove host from FreeIPA
  community.general.ipa_host:
    ipa_user: admin
    ipa_pass: "{{ vault_ipaadmin_password }}"
    ipa_host: "{{ vault_ipa_server }}"
    name: "{{ item.name }}.{{ foreman_domain }}"
    state: absent
    update_dns: true
  loop: "{{ vms }}"
  loop_control:
    label: "{{ item.name }}"
